"""
wrapper.py — Platform injection template for: Manager with at Least Five Direct Reports

How platform injection works for SQL problems:
  1. The contestant writes a SQL query in the editor (template.sql is the starter).
  2. The platform takes that SQL and creates:
         USER_SQL = \"\"\"<contestant's SQL>\"\"\"
  3. That line replaces the placeholder below at the PLATFORM INJECTION POINT.
  4. The combined Python file is submitted to Judge0 as Python (language_id: 71).
  5. stdin = JSON array of Employee rows (generated by generator.py).

stdin format:
  JSON array, one object per employee row:
  [{"id": 101, "name": "John", "department": "A", "managerId": null}, ...]

stdout format:
  One result row per line; multiple columns pipe-separated (|).
  Rows are sorted lexicographically (case-insensitive) for deterministic grading.
"""

import sys
import json
import sqlite3

# ===== PLATFORM INJECTION POINT =====
# The contestant's SQL query will be injected here as:
#   USER_SQL = \"\"\"SELECT ... FROM ...\"\"\";
# DO NOT MODIFY THIS LINE OR THE BLOCK BELOW.
USER_SQL = ""
# ===== END INJECTION POINT =====

# ---------------------------------------------------------------------------
# Schema & helpers (self-contained — no external imports needed in Judge0)
# ---------------------------------------------------------------------------

_SCHEMA_DDL = """
CREATE TABLE Employee (
    id          INTEGER,
    name        TEXT,
    department  TEXT,
    managerId   INTEGER
)
"""

_INSERT_SQL = "INSERT INTO Employee VALUES (:id, :name, :department, :managerId)"


def _create_db(rows):
    conn = sqlite3.connect(":memory:")
    cursor = conn.cursor()
    cursor.execute(_SCHEMA_DDL)
    for row in rows:
        cursor.execute(_INSERT_SQL, row)
    conn.commit()
    return conn


def _run_query(conn, sql):
    cursor = conn.cursor()
    cursor.execute(sql.strip())
    cols = [d[0] for d in cursor.description] if cursor.description else []
    rows = [tuple(r) for r in cursor.fetchall()]
    return rows, cols


def _format_output(rows):
    # Sort deterministically (case-insensitive) so grader gets consistent order
    rows_sorted = sorted(rows, key=lambda r: [
        str(v).lower() if v is not None else "" for v in r
    ])
    for row in rows_sorted:
        print("|".join("NULL" if v is None else str(v) for v in row))


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def execute_solution():
    try:
        raw = sys.stdin.read().strip()
        if not raw:
            return  # empty test → empty output

        rows = json.loads(raw)

        if not USER_SQL.strip():
            print("Error: No SQL query provided.", file=sys.stderr)
            sys.exit(1)

        conn = _create_db(rows)
        result_rows, _ = _run_query(conn, USER_SQL)
        conn.close()

        _format_output(result_rows)

    except json.JSONDecodeError as e:
        print(f"Input Error: invalid JSON — {e}", file=sys.stderr)
        sys.exit(1)
    except sqlite3.OperationalError as e:
        print(f"SQL Error: {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Runtime Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    execute_solution()
